FROM node:20-alpine AS base

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

# Development stage
FROM base AS development

EXPOSE 3000

CMD ["npm", "run", "start:dev"]

# Production stage  
FROM base AS production

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start:prod"]