services:
  mongodb:
    image: mongo:7.0
    container_name: imbasubvault-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: imbasubvault
    volumes:
      - mongodb_data:/data/db
    networks:
      - imbasubvault-network

  backend:
    build: .
    container_name: imbasubvault-backend
    restart: unless-stopped
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - imbasubvault-network

volumes:
  mongodb_data:

networks:
  imbasubvault-network:
    driver: bridge